language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd api
install:
  - npm install
services:
  - postgresql
env:
  global:
    - JWT_SECRET=kfngrjodsfmmsdodsosnrindsamawjfejfooeofnnwbqbd
    - CATERER_PASSWORD=password
    - CATERER_EMAIL=test@test.com
    - DATABASE_URL = "book_a_meal_test"
    - DATABASE_USER = "user1"
before_script:
  - psql -c 'CREATE DATABASE book_a_meal_test;' -U postgres
script: npm test
after_success:
  - npm run coverage
