language: node_js
env:
  global:
    - JWT_SECRET=ifeifeiw0rqdunio00nuububufjani;
    - NODE_ENV=test
node_js:
  - "8.12.0"
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - npm install -g nyc
script:
  - npm test
after_script:
  - npm run coverage
