language: node_js
env:
  global:
    - JWT_SECRET=kfngrjodsfmmsdodsosnrindsamawjfejfooeofnnwbqbd;
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd api
install:
  - npm install
before_script:
  - psql -c 'CREATE DATABASE book_a_meal;' -U user1
  - npm install -g nyc
script:
  - npm run test
after_success:
  - npm run coverage
