language: node_js
env:
  global:
    - JWT_SECRET=cool-secret;
    - NODE_ENV=test
node_js:
  - "8.12.0"
before_script:
  - psql -c 'CREATE DATABASE mealtest;' -U postgres
  - yarn global add nyc
script:
  - npm run coveralls
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
