language: node_js

node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd api
install:
  - npm install
services:
  - postgresql
env:
  global:
    - JWT_SECRET=kfngrjodsfmmsdodsosnrindsamawjfejfooeofnnwbqbd
before_script:
  - psql -c 'CREATE DATABASE book_a_meal;' -U postgres
  - npm install -g nyc
script:
  - npm run test
after_success:
  - npm run coverage
