language: node_js

node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd api
install:
  - npm install
services:
  - postgresql
env:
  global:
    - JWT_SECRET=kfngrjodsfmmsdodsosnrindsamawjfejfooeofnnwbqbd
    - CATERER_PASSWORD=password
    - CATERER_EMAIL=test@test.com
    - DATABASE_URL = "testdb"
    - DATABASE_USER = "user1"
before_script:
  - psql -c "DROP DATABASE testdb;" -U postgres
  - psql -c 'CREATE DATABASE testdb;' -U postgres
after_success:
  - npm run coverage
